prpduto_1 = str(input("Nome do produto: "))
preço_1 = float(input("Preço do produto: "))
prpduto_2 = str(input("Nome do produto: "))
preço_2 = float(input("Preço do produto: "))
prpduto_3 = str(input("Nome do produto: "))
preço_3 = float(input("Preço do produto: "))
prpduto_4 = str(input("Nome do produto: "))
preço_4 = float(input("Preço do produto: "))
lista = (prpduto_1, preço_1, prpduto_2, preço_2, prpduto_3, preço_3, prpduto_4, preço_4)
print(f"A sua Lista de compra ficou: \nProduto:{lista[0:2]}")
print(f"Produto:{lista[2:4]}")
print(f"Produto:{lista[4:6]}")
print(f"Produto:{lista[6:8]}")
