#tabuada

numero=int(input("vou fazer a tabuada dequal numero "))
vezes1=int(numero+0)
vezes2=int(numero+numero)
vezes3=int(numero*3)
vezes4=int(numero*4)
vezes5=int(numero*5)
vezes6=int(numero*6)
vezes7=int(numero*7)
vezes8=int(numero*8)
vezes9=int(numero*9)
vezes10=int(numero*10)

print(f"a tabuado do numero {numero} é  \n "  )
print(f" vezes 1= {vezes1}   \n "  )
print(f" vezes 2= {vezes2}   \n "  )
print(f" vezes 3= {vezes3}   \n "  )
print(f" vezes 4 ={vezes4}   \n "  )
print(f" vezes 5= {vezes5}   \n "  )
print(f" vezes 6= {vezes6}   \n "  )
print(f" vezes 7= {vezes7}   \n "  )
print(f" vezes 8= {vezes8}   \n "  )
print(f" vezes 9= {vezes9}   \n "  )
print(f" vezes 10= {vezes10}   \n "  )